export const APP_WRITE_ID = '65f560025b9d16f2fabc'
export const DB_ID = 'crm-database'
export const COLLECTION_DEALS = 'deals'
export const COLLECTION_CUSTOMERS = 'customers'
export const COLLECTION_COMMENTS = 'comments'
export const STORAGE_ID = 'storage'